services:
  php-fpm:
    build: ./docker/php
    volumes:
      - ./magento:/var/www/html
      - ./auth/auth.json:/root/.composer/auth.json
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - MAGENTO_ADMIN_USER=${MAGENTO_ADMIN_USER}
      - MAGENTO_ADMIN_PASS=${MAGENTO_ADMIN_PASS}
      - MAGENTO_ADMIN_EMAIL=${MAGENTO_ADMIN_EMAIL}
      - MAGENTO_BASE_URL=${MAGENTO_BASE_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql
      - elasticsearch
      - redis
    networks:
      - magento

  nginx:
    build: ./docker/nginx
    volumes:
      - ./magento:/var/www/html
      - ./certs:/etc/nginx/certs:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
      - varnish
    networks:
      - magento

  mysql:
    image: mysql:8.0
    command: --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - magento

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - magento

  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - magento

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    networks:
      - magento

  varnish:
    build: ./docker/varnish
    ports:
      - "6081:6081"
    depends_on:
      - php-fpm
    networks:
      - magento

volumes:
  db_data:
  elasticsearch_data:

networks:
  magento:
    driver: bridge
